name: My First Workflow

on: push

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print hello
        run: |
          echo "Hello, Vansh"
          echo "Welcome to GitHub Actions"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print bye
        run: |
          echo "Bye from work"