name: My First Workflow

on: push

jobs 1:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print name
        run: |
          echo "Hello, Vansh"
          echo "Welcome to GitHub Actions"

jobs 2:
  say-hello:
    run-on: ubuntu latest

    steps:
      - name: Print name
    run: |
    echo: "bye from work"